version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=security_system
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: always
    networks:
      - security_network

  migrations:
    build:
      context: .
      dockerfile: docker/migrations/Dockerfile
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=security_system
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - security_network

  face_recognition:
    build:
      context: .
      dockerfile: docker/face_recognition/Dockerfile
    volumes:
      # NOTE: Camera access through Docker doesn't work on macOS
      # On Linux, uncomment this line to use camera directly:
      # - /dev/video0:/dev/video0 
      - ./data:/app/data  # For sharing data between host and container
    environment:
      - CAMERA_ID=0
      - CONFIDENCE_THRESHOLD=0.5
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=security_system
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      # Upload mode is enabled by default for better macOS compatibility
      # This allows using uploaded images for face recognition instead of camera
      - USE_UPLOAD_MODE=true
    depends_on:
      postgres:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
    ports:
      - "8080:8080"  # Expose web interface port
    networks:
      - security_network

volumes:
  postgres_data:
    driver: local

networks:
  security_network:
    driver: bridge